# Generated by Django 4.2.2 on 2023-06-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestatlog',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stat',
            name='points',
            field=models.FloatField(),
        ),
    ]
