# Generated by Django 4.2.2 on 2023-07-04 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_tracker', '0004_remove_game_away_team_remove_game_home_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='team_1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='team_tracker.cflteam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='team_2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='team_tracker.cflteam'),
            preserve_default=False,
        ),
    ]
