# Generated by Django 4.2.2 on 2023-07-10 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_tracker', '0005_game_team_1_game_team_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamfantasyleague',
            name='last_calculated_game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team_tracker.game'),
        ),
    ]
